kind: RoleBinding
apiVersion: dac.authorization.k8s.io/v1
metadata:
  name: yamecloud
subjects:
- kind: ServiceAccount
  name: yamecloud
roleRef:
  kind: Role
  name: yamecloud
  apiGroup: dac.authorization.k8s.io
